<div class="row">
    <div class="col col-md-6">
        <form action="/application/index/create" name="form" method="POST" class="form-group">
            <label for="">Nome</label>
            <input type="text" name="nome" id="" class="form-control"/>
            <label for="">Cep</label>
            <input type="text" name="cep" id="" class="form-control"/>
            <label for="">Endereço</label>
            <input type="text" name="endereco" id="" class="form-control"/>
            <label for="">Número</label>
            <input type="text" name="numero" id="" class="form-control"/>
            <label for="">Complemento</label>
            <input type="text" name="complemento" id="" class="form-control"/>
            <label for="">Cidade</label>
            <input type="text" name="cidade" id="" class="form-control"/>
            <label for="">Bairro</label>
            <input type="text" name="bairro" id="" class="form-control"/>
            <label for="">Estado</label>
            <input type="text" name="estado" id="" class="form-control"/>
            <label for="">Telefone</label>
            <input type="text" name="telefone" id="" class="form-control"/>
            <label for="">Email</label>
            <input type="text" name="email" id="" class="form-control"/>
            <br>
            <div class="row">
                <div class="col col-md-6">
                    <button type="submit" class="btn btn-success">Enviar</button>
                </div>
            </div>
        </form>
    </div>
</div>