<div class="row">
    <div class="col col-md-6">
        <a href="/application/index/create" class="btn btn-success">Cadastrar</a>
    </div>
</div>
<div class="row">
    <div class="col col-md-12">
        <?php if (!empty($this->clientes)): ?>
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Endereço</th>
                    <th>Cidade</th>
                    <th>Bairro</th>
                    <th>Ação</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->clientes as $cliente): ?>
                    <tr>
                        <td><?= $cliente->getNome(); ?></td>
                        <td><?= $cliente->getEndereco(); ?></td>
                        <td><?= $cliente->getCidade(); ?></td>
                        <td><?= $cliente->getBairro(); ?></td>
                        <td>
                            <a href="/application/index/edit/<?php echo $cliente->getId(); ?>"
                               class="btn btn-default">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                            <a href="/application/index/delete/<?php echo $cliente->getId(); ?>" class="btn btn-danger">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                            <a href="/application/index/report/<?php echo $cliente->getId(); ?>" class="btn btn-success"
                               title="Exportar Detalhes do Usuário">
                                <i class="glyphicon glyphicon-file"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        <?php else: ?>
            <p class="alert alert-warning">Nenhum registro cadastrado.</p>
        <?php endif; ?>
    </div>
</div>
