<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $this->cliente->getNome(); ?></title>
</head>
<body>
    <h1 style="text-align: center">Dados Pessoais</h1>
    <table class="table">
        <thead>
        <tr>
            <td>Nome:</td>
            <td>Cidade:</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><?php echo $this->cliente->getNome(); ?></td>
            <td><?php echo $this->cliente->getCidade(); ?></td>
        </tr>
        </tbody>
    </table>
</body>
</html>